/** 登录 / 注册页文案（与 CollegeRide 语言设置 cr-lang 同步） */
export const AUTH_STRINGS = {
  zh: {
    title: "CollegeRide",
    subtitle: "请使用美国高等院校 .edu 邮箱（例如 @jhu.edu）登录或注册。",
    tab_login: "登录",
    tab_register: "注册",
    email: "邮箱",
    ph_email: "you@school.edu",
    password: "密码",
    password_confirm: "确认密码",
    display_name: "称呼",
    school_auto: "学校（根据邮箱自动识别）",
    school_preview_need_edu: "请输入有效的 .edu 邮箱，系统将自动匹配学校名称。",
    ph_display: "例如：Alex",
    btn_login: "登录",
    btn_register: "创建账户",
    btn_logging_in: "登录中…",
    btn_registering: "注册中…",
    err_email: "请输入有效邮箱",
    err_password_short: "密码至少 8 位",
    err_password_match: "两次密码不一致",
    err_display_name: "请输入称呼",
    err_generic: "出错了，请稍后重试",
    err_invalid_creds: "邮箱或密码不正确",
    err_email_used: "该邮箱已注册，请直接登录",
    err_not_edu: "仅允许 .edu 学校邮箱（美国院校电子邮件域名）。",
    err_tos_required: "请先阅读并勾选同意《服务条款》。",
    banner_local: "当前为浏览器本地账户（数据仅本机）。配置 Supabase 后可云端同步与多设备登录，详见项目 docs/AUTH.md。",
    logout: "退出登录",
    tos_prefix: "我已阅读并同意",
    tos_link: "《服务条款》",
    tos_suffix: "。",
  },
  en: {
    title: "CollegeRide",
    subtitle: "Sign in or register with a U.S. .edu school email (e.g. @jhu.edu).",
    tab_login: "Sign In",
    tab_register: "Register",
    email: "Email",
    ph_email: "you@school.edu",
    password: "Password",
    password_confirm: "Confirm Password",
    display_name: "Display Name",
    school_auto: "School (from your email)",
    school_preview_need_edu: "Enter a valid .edu address — your school name is detected automatically.",
    ph_display: "e.g. Alex",
    btn_login: "Sign In",
    btn_register: "Create Account",
    btn_logging_in: "Signing In…",
    btn_registering: "Creating Account…",
    err_email: "Enter a valid email address",
    err_password_short: "Password must be at least 8 characters",
    err_password_match: "Passwords do not match",
    err_display_name: "Enter your display name",
    err_generic: "Something went wrong. Try again.",
    err_invalid_creds: "Invalid email or password",
    err_email_used: "This email is already registered. Sign in instead.",
    err_not_edu: "Only .edu institutional email addresses are allowed.",
    err_tos_required: "Please read and check the box to agree to the Terms of Service.",
    banner_local:
      "Using on-device accounts (data stays on this browser). Configure Supabase for cloud sync and multi-device sign-in — see docs/AUTH.md.",
    logout: "Log Out",
    tos_prefix: "I have read and agree to the ",
    tos_link: "Terms of Service",
    tos_suffix: ".",
  },
};
